import math
print ("Задание 11")
x = input("Введите число x ") 
x = float(x)
y = input ("Введите число y ")
y = float (y)
z = input("Введите число z ")
z = float (z)
abs(x)
abs(y)
abs(z)
a = (math.sqrt(abs(x-1))-(pow(abs(y),1/3)) / (1+(pow(x,2)/2)+(pow(y,2)/4) ))
b = x*(math.atan(z)) + (math.exp(-(x+3)))
c = 3+(math.exp(y-1)) / 1+ (pow(x,2)) - abs(y-math.tan(z))
e = (a+y)*x+(y/pow(x,2)+4) / (pow(math.exp,-x-2))+ 1 / (pow(x,2)+4)
print ("А равно = %.2f" %a)
print ("B равно = %.2f" %b)
print ("C равно = %.2f" %c)
print ("C равно = %.2f" %e)

