import math
print ("Задание 53 ")
a = input("Введите a: ")
b = input("Введите b: ")
c = input("Введите c: ")
d = input("Введите d: ")
e = input("Введите e: ")
f = input("Введите f: ")
g = input("Введите g: ")
h = input("Введите h: ")
a = float(a)
b = float(b)
c = float(c)
d = float(d)
e = float(e)
f = float(f)
g = float(g)
h = float(h)
f1 = (a-e)*(h-f) - (b-f) * (g-e)
f2 = (c-e) * (h-f) - (d-f) * (g-e)
if ((f1>0) and (f2>2)) or ((f1<0) and (f2<0)): print("Принадлежат одной и той же полуплоскости")
else: print("Принадлежат одной и той же полуплоскости")
