import math
x = input ("Введіть x: ")
x = int(x)
y = input ("Введіть y: ")
y = int(y) 
if x>y: print("Минимальное число = ", y)
else: print("Минимальное число = ", x)
x = input ("Введіть x: ")
x = int(x)
y = input ("Введіть y: ")
y = int(y) 
if x>y: print("Максимальное число = ", x)
else: print("Максимальное число = ", y)
