import math
print ("Задание 44 ")
x = input("Введите X: ")
y = input("Введите Y: ")
x = float(x)
y = float(y)
if (x<0) and (y<0): print ("Модуль x = ", abs(x), "Модуль Y = ", abs(y))
x = input("Введите X: ")
y = input("Введите Y: ")
x = float(x)
y = float(y)
if (x<0) or (y<0): print ("X = ", x+0.5, "Y = ", y+0.5)
x = input("Введите X: ")
y = input("Введите Y: ")
x = float(x)
y = float(y)
if (x>=0) and (y>=0):print ("X = ", x/10, "Y = ", y/10)
if (x>2) or (x<0.5):print ("X = ", x/10, "Y = ", y/10)
if (y>2) or (y<0.5):print ("X = ", x/10, "Y = ", y/10)

