import math
print ("Задание 56 ")
a = input("Введите a: ")
b = input("Введите b: ")
c = input("Введите c: ")
x = input("Введите Розмеры отверстия : ")
y = input("Введите Розмеры отверстия : ")
a = float(a)
b = float(b)
c = float(c)
x = float(x)
y = float(y)
if ((a<=x) and (b<=y)) or ((b<=x) and (a<=y)) or ((a<=x) and (c<=y)) or ((c<=x) and (a<=y)) or ((c<=x) and (b<=y)) or ((b<=x) and (c<=y)): print ("Кирпич пройдет в отверстие")
else : print ("Кирпич не пройдет в отверстие")
